//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssingnentOnEFUsingStoredProecedure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Collections.Generic;

    public partial class StudentDBEntities1 : DbContext
    {
        public StudentDBEntities1()
            : base("name=StudentDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student> Students { get; set; }
    
        public virtual ObjectResult<AddStudent_Result> AddStudent(string std_ids)
        {
            var std_idsParameter = std_ids != null ?
                new ObjectParameter("Std_ids", std_ids) :
                new ObjectParameter("Std_ids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AddStudent_Result>("AddStudent", std_idsParameter);
        }
    
        public virtual ObjectResult<DeleteStudent_Result> DeleteStudent(string std_ids)
        {
            var std_idsParameter = std_ids != null ?
                new ObjectParameter("Std_ids", std_ids) :
                new ObjectParameter("Std_ids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DeleteStudent_Result>("DeleteStudent", std_idsParameter);
        }
    
        public virtual ObjectResult<GetStudent1_Result> GetStudent1(string std_ids)
        {
            var std_idsParameter = std_ids != null ?
                new ObjectParameter("Std_ids", std_ids) :
                new ObjectParameter("Std_ids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudent1_Result>("GetStudent1", std_idsParameter);
        }
    
        public virtual ObjectResult<GetStudentById_Result> GetStudentById(string std_ids)
        {
            var std_idsParameter = std_ids != null ?
                new ObjectParameter("Std_ids", std_ids) :
                new ObjectParameter("Std_ids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentById_Result>("GetStudentById", std_idsParameter);
        }
    
        public virtual ObjectResult<UpdateStudent_Result> UpdateStudent(string std_ids)
        {
            var std_idsParameter = std_ids != null ?
                new ObjectParameter("Std_ids", std_ids) :
                new ObjectParameter("Std_ids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UpdateStudent_Result>("UpdateStudent", std_idsParameter);
        }

        internal List<AddStudent_Result> AddStudent()
        {
            throw new NotImplementedException();
        }
    }
}
